In [1]:
import numpy as np
import h5py

### Creating

In [2]:
x = np.array([[11,12,13], [21,22,23]])
x

array([[11, 12, 13],
       [21, 22, 23]])

In [3]:
y = np.array([101, 201])
y

array([101, 201])

In [4]:
a = h5py.File("test.h5", "w")

In [5]:
a.create_dataset("x", data=x)

<HDF5 dataset "x": shape (2, 3), type "<i8">

In [6]:
a.create_dataset("y", data=y)

<HDF5 dataset "y": shape (2,), type "<i8">

In [7]:
a

<HDF5 file "test.h5" (mode r+)>

In [8]:
list(a.keys())

['x', 'y']

In [9]:
a["x"]

<HDF5 dataset "x": shape (2, 3), type "<i8">

In [10]:
a["y"]

<HDF5 dataset "y": shape (2,), type "<i8">

In [11]:
a["x"][:]

array([[11, 12, 13],
       [21, 22, 23]])

In [12]:
a["y"][:]

array([101, 201])

In [35]:
print(a)

<HDF5 file "test.h5" (mode r+)>


### Loading

In [13]:
b = h5py.File("test.h5", "r")

In [14]:
b

<HDF5 file "test.h5" (mode r+)>

In [15]:
list(b.keys())

['x', 'y']

In [16]:
b["x"]

<HDF5 dataset "x": shape (2, 3), type "<i8">

In [17]:
b["y"]

<HDF5 dataset "y": shape (2,), type "<i8">

In [18]:
b["x"][:]

array([[11, 12, 13],
       [21, 22, 23]])

In [19]:
b["y"][:]

array([101, 201])

In [22]:
np.array(b["x"])

array([[11, 12, 13],
       [21, 22, 23]])

### Creating and Loading with Pandas

In [23]:
import pandas as pd

In [24]:
c = {"c1" : ["male", "female", "female"],
    "c2" : [11,21,31]}

df = pd.DataFrame(c)
df

c1  c2
0    male  11
1  female  21
2  female  31

In [29]:
## creating
df.to_hdf("test_pd.h5", key="c", mode="w")

In [30]:
df

c1  c2
0    male  11
1  female  21
2  female  31

In [31]:
## loading
c = pd.read_hdf("test_pd.h5")

In [32]:
c

c1  c2
0    male  11
1  female  21
2  female  31

In [33]:
c.c1

0      male
1    female
2    female
Name: c1, dtype: object

In [34]:
c.c2

0    11
1    21
2    31
Name: c2, dtype: int64