In [2]:
import numpy as np

In [3]:
# avoid for loop:
# d[j,k] =  sum_i a[j,i] * b[k,i]

a = np.array([[11,12],[21,22],[31,32]])
b = np.array([[0.1,0.2],[10,20]])
print(a)
print(b)

c = a[:,:,np.newaxis] * b.T[np.newaxis,:,:]
d = np.sum(c,axis=1)
print(d)

[[11 12]
 [21 22]
 [31 32]]
[[ 0.1  0.2]
 [10.  20. ]]
[[  3.5 350. ]
 [  6.5 650. ]
 [  9.5 950. ]]


In [6]:
# d[t,j] = sum_i a[t,i] - b[i,j]

a = np.array([[11,12],[21,22],[31,32]])
print(a)

b = np.array([[1,2],[10,20]])
print(b)

c = a[:,:,np.newaxis] - b[np.newaxis,:,:]
d = np.sum(c,axis=1)
print(d)

[[11 12]
 [21 22]
 [31 32]]
[[ 1  2]
 [10 20]]
[[12  1]
 [32 21]
 [52 41]]


In [8]:
# e[t,j] = mean_i (a[t,i] - b[i,j])**2
e = np.mean(c**2,axis=1)
print(e)

[[ 52.   72.5]
 [272.  182.5]
 [692.  492.5]]


In [9]:
a = np.array([[11,12],[21,22],[31,32]])
print(a)

[[11 12]
 [21 22]
 [31 32]]
