In [1]:
import numpy as np

In [3]:
#0) generate sequence
L=3
N=2

S = np.array([[1., -1.], [2.,0.], [3., 4.]])
print('S:')
print(S)
print('S[1,0]:',S[1,0])

S:
[[ 1. -1.]
 [ 2.  0.]
 [ 3.  4.]]
('S[1,0]:', 2.0)


In [4]:
# 1) Calculate covariance by traditional method
m = np.mean(S, axis=0)
dS = S - m
print('dS:')
print(dS)

print('Cij:')
C = np.empty((N,N))
for i in range(N):
   for j in range(N):
      C[i,j] = np.mean(dS[:, i] * dS[:, j])
      #print(i,j,C[i,j])
print(C)

dS:
[[-1. -2.]
 [ 0. -1.]
 [ 1.  3.]]
Cij:
[[0.66666667 1.66666667]
 [1.66666667 4.66666667]]


In [5]:
# 2) by matrix transpose:
print('Cij by matrix transpose:' )
C2 = np.matmul(dS.T,dS)/L
print(C2)

Cij by matrix transpose:
[[0.66666667 1.66666667]
 [1.66666667 4.66666667]]


In [6]:
# 3) by python function:
C3 = np.cov(S.T,bias=True)  ## need to add bias = True
print('Cij by np.cov:' )
print(C3)

Cij by np.cov:
[[0.66666667 1.66666667]
 [1.66666667 4.66666667]]


In [7]:
# 4) by python function:
C4 = np.cov(S,rowvar=False,bias=True)  ## need to add bias = True
print('Cij by np.cov, rowvar=False:' )
print(C4)

Cij by np.cov, rowvar=False:
[[0.66666667 1.66666667]
 [1.66666667 4.66666667]]


In [8]:
St = np.array([[1,2],[0,0],[2,1]])
print('St:')
print(St)

mSt = np.mean(St, axis=0)
dSt = St - mSt

print(dS)
print(dSt)

C11 = np.empty((N,N))
for i in range(N):
   for j in range(N):
      C11[i,j] = np.mean(dSt[:, i] * dS[:, j])
print(C11)

St:
[[1 2]
 [0 0]
 [2 1]]
[[-1. -2.]
 [ 0. -1.]
 [ 1.  3.]]
[[ 0.  1.]
 [-1. -1.]
 [ 1.  0.]]
[[ 0.33333333  1.33333333]
 [-0.33333333 -0.33333333]]


In [9]:
def cross_cov(a,b):
   da = a - np.mean(a, axis=0)
   db = b - np.mean(b, axis=0)
   return np.matmul(da.T,db)/a.shape[0]

C12 = cross_cov(St,S)
print(C12)

[[ 0.33333333  1.33333333]
 [-0.33333333 -0.33333333]]
