Find difference between 2 arrays a1 and a2.

In [1]:
import numpy as np

In [2]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
a2 = np.array([[4,5,6],[7,8,9],[1,1,1]])
a2

array([[4, 5, 6],
       [7, 8, 9],
       [1, 1, 1]])

In [4]:
a1_rows = a1.view([('', a1.dtype)] * a1.shape[1])
a2_rows = a2.view([('', a2.dtype)] * a2.shape[1])
a3 = np.setdiff1d(a1_rows, a2_rows).view(a1.dtype).reshape(-1, a1.shape[1])

print(a3)

[[1 2 3]]
