In [1]:
import sys
import numpy as np
from scipy.spatial import distance

In [2]:
# for only 2 sequences:
a = np.array([1,2,3,5,7])
b = np.array([2,1,3,4,7])

dst = distance.hamming(a,b)
print(dst)

0.6


In [3]:
# for a matrix:
a = np.array([[1,2,3,5,7],[2,1,3,4,7],[1,2,3,4,7],[0,2,3,8,2]])
print(a)

[[1 2 3 5 7]
 [2 1 3 4 7]
 [1 2 3 4 7]
 [0 2 3 8 2]]


In [4]:
t,n = a.shape
print(t,n)

(4, 5)


In [5]:
dst = distance.pdist(a, 'hamming')
print(dst)

[0.6 0.2 0.6 0.4 0.8 0.6]


In [6]:
dst2 = distance.squareform(dst)
print(dst2)

[[0.  0.6 0.2 0.6]
 [0.6 0.  0.4 0.8]
 [0.2 0.4 0.  0.6]
 [0.6 0.8 0.6 0. ]]


In [7]:
theta = 0.2
ma = dst2 <= theta
print(ma)

[[ True False  True False]
 [False  True False False]
 [ True False  True False]
 [False False False  True]]


In [8]:
# sum over every sequence:
ma2 = (dst2 <= theta).sum(axis=1)
print(ma2)

[2 1 2 1]
