In [1]:
import numpy as np

In [2]:
a = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34],[41,42,43,44]])
print(a)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]


In [3]:
# insert a zero-column to the column 2
a = np.insert(a,2,0.,axis=1)
print(a)

[[11 12  0 13 14]
 [21 22  0 23 24]
 [31 32  0 33 34]
 [41 42  0 43 44]]


In [4]:
# insert a zero-column to the column 5
a = np.insert(a,5,0.,axis=1)
print(a)

[[11 12  0 13 14  0]
 [21 22  0 23 24  0]
 [31 32  0 33 34  0]
 [41 42  0 43 44  0]]


In [5]:
# insert a zero-row to the row 2
a = np.insert(a,2,0.,axis=0)
print(a)

[[11 12  0 13 14  0]
 [21 22  0 23 24  0]
 [ 0  0  0  0  0  0]
 [31 32  0 33 34  0]
 [41 42  0 43 44  0]]


In [6]:
# insert a zero-row to the row 5
a = np.insert(a,5,0.,axis=0)
print(a)

[[11 12  0 13 14  0]
 [21 22  0 23 24  0]
 [ 0  0  0  0  0  0]
 [31 32  0 33 34  0]
 [41 42  0 43 44  0]
 [ 0  0  0  0  0  0]]


In [7]:
a = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34],[41,42,43,44]])
print(a)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]


In [8]:
# insert 0 as 2nd and 5th columns
ilist = [2,5]

for i in ilist:
    a = np.insert(a,i,0,axis=1)
    print(a)

[[11 12  0 13 14]
 [21 22  0 23 24]
 [31 32  0 33 34]
 [41 42  0 43 44]]
[[11 12  0 13 14  0]
 [21 22  0 23 24  0]
 [31 32  0 33 34  0]
 [41 42  0 43 44  0]]


In [9]:
# delele column ilist:
a = np.delete(a,ilist[::-1],axis=1)
print(a)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]
