In [3]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

In [4]:
x = [5.05, 6.75, 3.21, 2.66]
y = [1.65, 26.5, -5.93, 7.96]
slope, intercept, r_value, p_value, std_err = stats.linregress(x,y)

a = np.random.rand(4,4)
b = np.random.rand(4,4)

#a1 = a.reshape(16,1)
R = stats.linregress(a.flatten(),b.flatten())[2]

print(a)

[[0.12583969 0.47217556 0.89449712 0.73134618]
 [0.29768367 0.26034219 0.68927593 0.91434248]
 [0.92356582 0.61600927 0.51477442 0.67671286]
 [0.90773786 0.87910228 0.17943669 0.02525393]]
