In [1]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [2]:
s0 = np.array([[2,3,2,3],[1,2,0,1],[1,1,0,2]])
s0

array([[2, 3, 2, 3],
       [1, 2, 0, 1],
       [1, 1, 0, 2]])

In [3]:
n_var = s0.shape[1]
mx = np.array([len(np.unique(s0[:,i])) for i in range(n_var)])
mx_cumsum = np.insert(mx.cumsum(),0,0)
i1i2 = np.stack([mx_cumsum[:-1],mx_cumsum[1:]]).T 

In [4]:
mx

array([2, 3, 2, 3])

In [5]:
mx_cumsum

array([ 0,  2,  5,  7, 10])

In [7]:
onehot_encoder = OneHotEncoder(sparse=False,categories='auto')
s = onehot_encoder.fit_transform(s0)
s

array([[0., 1., 0., 0., 1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 1., 0., 0., 1., 0.]])

In [9]:
aa_last = mx_cumsum[1:] - 1
aa_last

array([1, 4, 6, 9])

In [10]:
i0 = 1

i1,i2 = i1i2[i0,0],i1i2[i0,1]

y_col = np.arange(i1,i2)
print(y_col)

[2 3 4]


In [12]:
# find union (columns to delete)
aa_del = np.union1d(aa_last,y_col)
aa_del

array([1, 2, 3, 4, 6, 9])

In [13]:
# delete s at the positions of aa_del
x = np.delete(s,aa_del,axis=1)
x

array([[0., 0., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 0., 1.]])

In [18]:
mx_sum = mx.sum()

aa_all = np.arange(mx_sum)
aa_all

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
aa_remain = np.setdiff1d(aa_all,aa_del)
aa_remain

array([0, 5, 7, 8])