In [1]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [2]:
s0 = np.array([[11,12],[11,13],[12,11]])
print(s0)
l,n = s0.shape

[[11 12]
 [11 13]
 [12 11]]


In [3]:
mx = np.array([len(np.unique(s0[:,i])) for i in range(n)])
print(mx)

[2 3]


In [4]:
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
s = onehot_encoder.fit_transform(s0)
print(s.shape)
print(s)

(3, 5)
[[1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1.]
 [0. 1. 1. 0. 0.]]


In [5]:
mx_cumsum = np.insert(mx.cumsum(),0,0)
i1i2 = np.stack([mx_cumsum[:-1],mx_cumsum[1:]]).T

In [6]:
for i in range(n):
    print(i1i2[i,0],i1i2[i,1])

(0, 2)
(2, 5)
