In [1]:
import numpy as np

In [19]:
# 2D to 3D: (l,n^2) --> (l,n,n)
x = np.arange(8).reshape(2,4)
print(x)
print(x.shape)

[[0 1 2 3]
 [4 5 6 7]]
(2, 4)


In [25]:
#y = x.reshape(np.roll(x.shape))
y = x.reshape(2,2,2)
print(y)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [9]:
y.shape

(4, 2)

In [12]:
# 3D --> 2D (l,n,n) --> (lxn,n)
a = np.arange(8).reshape(2,2,2)
print(a)
print(a.shape)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
(2, 2, 2)


In [13]:
print(a[0])

[[0 1]
 [2 3]]


In [15]:
b = a.reshape(-1,a.shape[0])
print(b)
print(b.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)
