In [2]:
# select only some columns that satisfies certain conditions
import numpy as np

s = np.array([[1.,-1.,1.,-1.],[1.,1.,1.,-1.],[-1.,-1.,1.,1.]])
print(s)

[[ 1. -1.  1. -1.]
 [ 1.  1.  1. -1.]
 [-1. -1.  1.  1.]]


In [8]:
l = s.shape[0]
n = s.shape[1]
print(l,n)


(3, 4)


In [9]:
f = [(s[:,i] == -1).sum()/float(l) for i in range(n)]
print(f)

[0.3333333333333333, 0.6666666666666666, 0.0, 0.6666666666666666]


In [19]:
cols = [i for i in range(n) if 0.1 < f[i] and f[i] < 0.5]
print(cols)

[0]


In [20]:
s1 = s[:,cols]
print(s1)

[[ 1.]
 [ 1.]
 [-1.]]
