In [2]:
import numpy as np

In [3]:
a = np.array([[1,10.], [2.,20.], [3.,30.]])
print(a)

b = np.array([[0.1],[0.2]])
print(b)

c = a - b.T
print(c)

[[ 1. 10.]
 [ 2. 20.]
 [ 3. 30.]]
[[0.1]
 [0.2]]
[[ 0.9  9.8]
 [ 1.9 19.8]
 [ 2.9 29.8]]


In [4]:
a = np.array([[11,12,13], [21,22,23]])
print(a)
b = np.array([1,2])
print(b)

b = b.reshape((-1,1))
print(b)
c = a-b
print(c)

[[11 12 13]
 [21 22 23]]
[1 2]
[[1]
 [2]]
[[10 11 12]
 [19 20 21]]


In [8]:
a = np.array([[11,12], [21,22], [31,32]])
print(a)

b = np.array([1,2])
print(b)

a-b

[[11 12]
 [21 22]
 [31 32]]
[1 2]


array([[10, 10],
       [20, 20],
       [30, 30]])