In [1]:
## sorted based on std
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("test.csv", sep=",", index_col=None)
df

ENSG1  ENSG2  ENSG3  ENSG4
0     11     12     13     14
1     21    200   2000     14
2     31    300   3000     14
3     41    400   4000     15

In [3]:
genes = [col for col in df.columns if col.startswith('ENSG')]
genes

['ENSG1', 'ENSG2', 'ENSG3', 'ENSG4']

In [4]:
n_genes = len(genes)
n_genes

4

In [5]:
a = df[genes[0]].values
a

array([11, 21, 31, 41])

In [6]:
std = np.std(a)
std

11.180339887498949

In [7]:
stds = [np.std(df[genes[i]].values) for i in range(n_genes)]
stds

[11.180339887498949, 143.3596874996594, 1474.0782501278554, 0.4330127018922193]

In [8]:
np.sort(stds)[::-1]

array([1.47407825e+03, 1.43359687e+02, 1.11803399e+01, 4.33012702e-01])

In [9]:
i = np.argsort(stds)[::-1]
i

array([2, 1, 0, 3])

In [10]:
genes_sorted = [genes[ii] for ii in i]
genes_sorted

['ENSG3', 'ENSG2', 'ENSG1', 'ENSG4']

In [11]:
df_sorted = df[genes_sorted]
df_sorted

ENSG3  ENSG2  ENSG1  ENSG4
0     13     12     11     14
1   2000    200     21     14
2   3000    300     31     14
3   4000    400     41     15

In [12]:
df_sorted.to_csv("test_sorted.csv", index=None)

In [13]:
df = pd.read_csv("test_sorted.csv", index_col=None)
df

ENSG3  ENSG2  ENSG1  ENSG4
0     13     12     11     14
1   2000    200     21     14
2   3000    300     31     14
3   4000    400     41     15