In [1]:
import numpy as np

In [2]:
a = np.array([[11,12],[13,14]])
print(a)

[[11 12]
 [13 14]]


In [3]:
b = np.array([[21,22],[23,24]])
print(b)

[[21 22]
 [23 24]]


In [4]:
c = np.array([[31,32],[33,34]])
print(c)

[[31 32]
 [33 34]]


In [5]:
d = np.dstack((a,b,c))
print(d.shape)
print(d)

(2, 2, 3)
[[[11 21 31]
  [12 22 32]]

 [[13 23 33]
  [14 24 34]]]


In [6]:
d[:,:,0] # a

array([[11, 12],
       [13, 14]])

In [7]:
d[:,:,1] # b

array([[21, 22],
       [23, 24]])

In [8]:
d[:,:,2] # c

array([[31, 32],
       [33, 34]])