In [7]:
import numpy as np
from numpy import pi

In [8]:
a = np.array([11,12,13,14,15])
print(a)
print(type(a))

print(a[1:3]) # element 2 and 3: 12, 13

print(a[1:-1]) # 12,13,14

# omitted boundaries are assumed to the the beginning (or end) of the list

# grab first three elements
print(a[:3])
# grab last two elements
print(a[-2:])
# every other elements
print(a[::2])

[11 12 13 14 15]
<type 'numpy.ndarray'>
[12 13]
[12 13 14]
[11 12 13]
[14 15]
[11 13 15]


In [9]:
# derivative
x = np.array([0, 1, 1.5, 3])
y = np.array([1, 2, 3, 1])

dy = y[1:] - y[:-1]
dx = x[1:] - x[:-1]

dy_dx = dy/dx
print(dy_dx)

[ 1.          2.         -1.33333333]


In [10]:
# middle point
center_x = (x[1:] + x[:-1])/2.
print(center_x)

[0.5  1.25 2.25]


In [11]:
# multiple dimensions
r = np.arange(6)
print(r)

r = r.reshape(2,3)  # 2 rows and 3 columns
print(r)

print(r[-1,-1])
print(r[0,1])
print(r[1,1:])
print(r[:1,:1])

print(r[:1,:1].shape)
r[:,2] = 100
print(r)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
5
1
[4 5]
[[0]]
(1, 1)
[[  0   1 100]
 [  3   4 100]]


In [12]:
# 3 dimensions
r = np.arange(24).reshape(3,2,4) # z, y, x (depth, row, column)
print(r)


[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [13]:
# copy and modify
a = np.array([1,2,3,4,5])
print(a)

b = a[1:3]
print(b)
b[0] = 100
print(b)
print(a) # a is also changed as b

c = a[1:3].copy() # a is not changed
c[0]=200
print(c)
print(a)

# add
g = np.zeros(10)
g[:len(a)] = a  # a is not changed
print(g)

g[0] = 10
print(g)
print(a)

[1 2 3 4 5]
[2 3]
[100   3]
[  1 100   3   4   5]
[200   3]
[  1 100   3   4   5]
[  1. 100.   3.   4.   5.   0.   0.   0.   0.   0.]
[ 10. 100.   3.   4.   5.   0.   0.   0.   0.   0.]
[  1 100   3   4   5]


In [23]:
# Fancy indexing

a = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34,35]])
print(a)
print(type(a))
print(a.shape)

print(a[1])

# 1) indexing by position
indices = [1,2]
c = a[indices]
print(c)

d = (a[1],a[2])
print(d)

# 2) indexing with booleans
mask = a < 50
b = a[mask]
print(b)
print(type(b))
print(b.shape)

# 3)
#b = a[a % 2 ==0]
#print(b)

[list([11, 12, 13, 14]) list([21, 22, 23, 24]) list([31, 32, 33, 34, 35])]
<type 'numpy.ndarray'>
(3,)
[21, 22, 23, 24]
[list([21, 22, 23, 24]) list([31, 32, 33, 34, 35])]
([21, 22, 23, 24], [31, 32, 33, 34, 35])
[]
<type 'numpy.ndarray'>
(0,)


In [24]:
# Calculation in numpy
a = np.arange(6).reshape(2,3)
print(a)

print(a.sum())
print(a.prod()) # product
print(a.mean())
print(a.std())
print(a.max())
print(a.min())

print(a.argmin()) # linear dimension
print(a.argmax()) # linear dimension
print(np.unravel_index(a.argmin(),a.shape)) # correct dimension
print(np.unravel_index(a.argmax(),a.shape)) # correct dimension

# sum in each column/row
print(a)
print(a.sum(axis=0)) # for each column
print(a.sum(axis=1)) # for each row
print(a.sum(axis=-1)) # for each row

[[0 1 2]
 [3 4 5]]
15
0
2.5
1.707825127659933
5
0
0
5
(0, 0)
(1, 2)
[[0 1 2]
 [3 4 5]]
[3 5 7]
[ 3 12]
[ 3 12]


In [25]:
# 2D
a = np.array([[1.,10.,100],[2,20,200]])
print(a)

# zeros, ones, empty
a = np.zeros((2,3))
print(a)

a = np.ones((2,3))
print(a)

b = np.empty((2,3)) # the initial input may vary
print(b)

# create an array
a = np.linspace(0,2,9) # 9 numbers from 0 to 2
print(a)

a = np.linspace(0,2*pi,10)
print(a)

[[  1.  10. 100.]
 [  2.  20. 200.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]


In [26]:
# Basic operations
a = np.array([[1,2],[3,4]])
print(a)
b = np.array([[1,5],[2,1]])
print(b)

print(a*b) # elementwise product
print(np.dot(a,b)) # matrix product

[[1 2]
 [3 4]]
[[1 5]
 [2 1]]
[[ 1 10]
 [ 6  4]]
[[ 5  7]
 [11 19]]


In [27]:
# to modify an existing array rather than create a new one
b +=a  # b = b + a
print(b)

a *=3   # a = a*3
print(a)

print(a.sum())
print(a.min())
print(a.max())
print(a.sum(axis=0)) # sum of each column
print(a.sum(axis=1)) # sum of each row
print(a.min(axis=1)) # min of each row
print(a.cumsum(axis=1)) # cumulative of each row

[[2 7]
 [5 5]]
[[ 3  6]
 [ 9 12]]
30
3
12
[12 18]
[ 9 21]
[3 9]
[[ 3  9]
 [ 9 21]]


In [28]:
# Universal Functions
a = np.array([0,1,2])
print(a)
print(np.exp(a))
print(np.sqrt(a))

b = np.array([-1, 2, 3])
print(a)
print(b)
c = np.add(a,b) # = a + b?
print(c)

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[0 1 2]
[-1  2  3]
[-1  3  5]


In [29]:
# Indexing, Slicing and Iterating
# 1D

a = np.array([10, 20, 30, 40, 50, 60, 70])
print(a)

print(a[2])
print(a[1:4])
a[:3:2] = -100 # equivalent to a[0:3:2]=-100;
# set from index 0 to index 3, step = 2
print(a)
b = a[::-1] # reversed
print(b)

[10 20 30 40 50 60 70]
30
[20 30 40]
[-100   20 -100   40   50   60   70]
[  70   60   50   40 -100   20 -100]


In [30]:
# multiple dimensions
a = np.array([[10,20,30,40],[100,200,300,400]])
print(a)
print(a[1,2])
print(a[:,2])
print(a[-1]) # the last row, equivalent to a[-1,:]

[[ 10  20  30  40]
 [100 200 300 400]]
300
[ 30 300]
[100 200 300 400]


In [31]:
# Iterating
print(a)
# each row
for row in a:
    print(row)
# each element
for element in a.flat:
    print(element)

[[ 10  20  30  40]
 [100 200 300 400]]
[10 20 30 40]
[100 200 300 400]
10
20
30
40
100
200
300
400


In [32]:
# Shape Manipulation
a = np.array([[10,20,30,40],[100,200,300,400]])
print(a)
print(a.ravel()) # convert to 1D

print(a.reshape(4,2))
print(a) # it does not change the original one
print(a.T) # transposed

print(a)
print(a.reshape(4,-1)) # -1 means other dimension is automatically calculated

[[ 10  20  30  40]
 [100 200 300 400]]
[ 10  20  30  40 100 200 300 400]
[[ 10  20]
 [ 30  40]
 [100 200]
 [300 400]]
[[ 10  20  30  40]
 [100 200 300 400]]
[[ 10 100]
 [ 20 200]
 [ 30 300]
 [ 40 400]]
[[ 10  20  30  40]
 [100 200 300 400]]
[[ 10  20]
 [ 30  40]
 [100 200]
 [300 400]]


In [33]:
# Stacking together different arrays
a = np.array([[10,20,30],[100,200,300]])
b = np.array([[0.1,0.2,0.3],[1,2,3]])
print(a)
print(b)
c = np.vstack((a,b)) # vertical stack
print(c)
print(c.shape)

c = np.hstack((a,b)) # horizontal stack
print(c)
print(c.shape)

[[ 10  20  30]
 [100 200 300]]
[[0.1 0.2 0.3]
 [1.  2.  3. ]]
[[1.e+01 2.e+01 3.e+01]
 [1.e+02 2.e+02 3.e+02]
 [1.e-01 2.e-01 3.e-01]
 [1.e+00 2.e+00 3.e+00]]
(4, 3)
[[1.e+01 2.e+01 3.e+01 1.e-01 2.e-01 3.e-01]
 [1.e+02 2.e+02 3.e+02 1.e+00 2.e+00 3.e+00]]
(2, 6)


In [34]:
# stack 1D arrays as columns into a 2D array
a = np.array([[10,20],[0.1,0.2]])
b = np.array([100,200])
print(a)
print(b)
c = np.column_stack((a,b))
print(c)

c = np.row_stack((a,b))
print(c)

[[10.  20. ]
 [ 0.1  0.2]]
[100 200]
[[1.e+01 2.e+01 1.e+02]
 [1.e-01 2.e-01 2.e+02]]
[[1.e+01 2.e+01]
 [1.e-01 2.e-01]
 [1.e+02 2.e+02]]


In [35]:
# Splitting one array into several smaller ones
a = np.array([[10,20,30,40,50,60],[100,200,300,400,500,600]])
print(a)
print(np.hsplit(a,3)) # split into 3, horizonal axis
print(np.hsplit(a,(1,3))) # split between the 2nd and the 3rd column

print(a)
print(np.vsplit(a,2)) # split into 2, vertical axis

[[ 10  20  30  40  50  60]
 [100 200 300 400 500 600]]
[array([[ 10,  20],
       [100, 200]]), array([[ 30,  40],
       [300, 400]]), array([[ 50,  60],
       [500, 600]])]
[array([[ 10],
       [100]]), array([[ 20,  30],
       [200, 300]]), array([[ 40,  50,  60],
       [400, 500, 600]])]
[[ 10  20  30  40  50  60]
 [100 200 300 400 500 600]]
[array([[10, 20, 30, 40, 50, 60]]), array([[100, 200, 300, 400, 500, 600]])]


In [36]:
# Copies and views
# 1) No copies at all
a = np.array([[10,20,30],[100,200,300]])
print(a)

b = a # no new object is created, b and a are two names for the same array
b.shape = 3,2
print(a.shape)  # a change as b change


[[ 10  20  30]
 [100 200 300]]
(3, 2)


In [37]:
# 2) View or Shallow Copy
a = np.array([[10,20,30],[100,200,300]])
print(a)

c = a.view() # share the same data, but the shape of two array can be different

print(c.shape)
c[0,1]= 1000
print(c)
print(a)

[[ 10  20  30]
 [100 200 300]]
(2, 3)
[[  10 1000   30]
 [ 100  200  300]]
[[  10 1000   30]
 [ 100  200  300]]


In [38]:
# Slicing an array return a view of it:
print(a)
c = a[:,0:2]
print(c)
c[1,:]=2000
print(c)
print(a)

[[  10 1000   30]
 [ 100  200  300]]
[[  10 1000]
 [ 100  200]]
[[  10 1000]
 [2000 2000]]
[[  10 1000   30]
 [2000 2000  300]]


In [39]:
# 3) Deep copy
a = np.array([[10,20,30],[100,200,300]])
print(a)
b = a.copy()

b[1,1] = 0
print(b)
print(a)

[[ 10  20  30]
 [100 200 300]]
[[ 10  20  30]
 [100   0 300]]
[[ 10  20  30]
 [100 200 300]]


In [40]:
# Index
a = np.array([[10,20,30],[100,200,300]])
print(a)

b = a[a>20]
print(b)

# another way:
b = (a > 20) & (a <200)
c = a[b]
print(c)

# The ix_() function
a = np.array([1,2])
b = np.array([2])
c = np.array([4,3])
print(a)
print(b)
print(c)

ax,bx,cx = np.ix_(a,b,c)
print(ax)
print(bx)
print(cx)

print(ax.shape)
print(bx.shape)
print(cx.shape)

result = ax + bx*cx
print(result)
print(result[0,0,1])
print(a[0] + b[0]*c[1])

[[ 10  20  30]
 [100 200 300]]
[ 30 100 200 300]
[ 30 100]
[1 2]
[2]
[4 3]
[[[1]]

 [[2]]]
[[[2]]]
[[[4 3]]]
(2, 1, 1)
(1, 1, 1)
(1, 1, 2)
[[[ 9  7]]

 [[10  8]]]
7
7


In [41]:
# Linear Algebra
a = np.array([[1.,2.],[3.,4.]])
print(a)

b = a.transpose() # transpose matrix
print(b)

b = np.linalg.inv(a) # inverse matrix
print(b)

u = np.eye(2)   # unit 2x2 matrix; "eye" represents "I"
print(u)

print(a)
y = np.array([[5.],[7.]])
print(y)
b = np.linalg.solve(a, y)  # b = y/a
print(b)

[[1. 2.]
 [3. 4.]]
[[1. 3.]
 [2. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 0.]
 [0. 1.]]
[[1. 2.]
 [3. 4.]]
[[5.]
 [7.]]
[[-3.]
 [ 4.]]


In [42]:
# Stacking together different arrays
a = np.array([[10,20,30],[100,200,300]])
b = np.array([[0.1,0.2,0.3],[1,2,3]])
print(a)
print(b)
c = np.vstack((a,b)) # vertical stack
print(c)
print(c.shape)

c = np.hstack((a,b)) # horizontal stack
print(c)
print(c.shape)

[[ 10  20  30]
 [100 200 300]]
[[0.1 0.2 0.3]
 [1.  2.  3. ]]
[[1.e+01 2.e+01 3.e+01]
 [1.e+02 2.e+02 3.e+02]
 [1.e-01 2.e-01 3.e-01]
 [1.e+00 2.e+00 3.e+00]]
(4, 3)
[[1.e+01 2.e+01 3.e+01 1.e-01 2.e-01 3.e-01]
 [1.e+02 2.e+02 3.e+02 1.e+00 2.e+00 3.e+00]]
(2, 6)


In [43]:
# linear list
a = np.linspace(2,20,10)
print(a)

a = a.tolist()
print(a)

#=========================================================

a = np.arange(3)
print(a)

a = np.arange(3.0)
print(a) #[0.,1.,2.]

a = np.arange(2,8)
print(a) # [2, 3, 4, 5, 6, 7]

a = np.arange(2,8,2)
print(a) # [2, 4, 6]

a = np.arange(-5,8,3)
print(a) # [-5, -2, 1, 4, 7]

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
[2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0, 18.0, 20.0]
[0 1 2]
[0. 1. 2.]
[2 3 4 5 6 7]
[2 4 6]
[-5 -2  1  4  7]


In [45]:
# del rows of matrix
nens=2

S01 = np.array([[1,10.], [2.,20.], [3.,30.], [4.,40.],[5.,50.],[6.,60.]])
print(S01)

L0 = S01.shape[0]
print(L0)

L01=L0/nens
print(L01)

rows_del = [i for i in range(L0) if (i+1)%L01==0]
print(rows_del)
S = np.delete(S01,rows_del,axis=0)
print(S)
print('\n'*3)
rows_del = [i for i in range(L0) if (i+1)%L01==1]
print(rows_del)
S1 =np.delete(S01,rows_del,axis=0)
print(S1)

[[ 1. 10.]
 [ 2. 20.]
 [ 3. 30.]
 [ 4. 40.]
 [ 5. 50.]
 [ 6. 60.]]
6
3
[2, 5]
[[ 1. 10.]
 [ 2. 20.]
 [ 4. 40.]
 [ 5. 50.]]




[0, 3]
[[ 2. 20.]
 [ 3. 30.]
 [ 5. 50.]
 [ 6. 60.]]


In [46]:
# multiplication of matrix elements
a = np.array([[11,12.], [21.,22.]])
print(a)

b = np.array([[1.1,1.2],[2.1,2.2]])
print(b)

c = 1-b[0,:]
print(c)


#c = np.reshape(c,(2,1))

#print(c)

d = a*c
print(d)

d2 = np.multiply(a,c) 
print(d2)

d3 = np.multiply(c,a) 
print(d3)

#===============================================================================
a = np.array([[11,12.], [21.,22.],[31,32]])
print(a)

b = np.array([[0.1,0.2],[100,200]])
print(b)

#c = a*b
c = np.multiply(a,b[:,0])
print(c)
print(a*b[:,0])

[[11. 12.]
 [21. 22.]]
[[1.1 1.2]
 [2.1 2.2]]
[-0.1 -0.2]
[[-1.1 -2.4]
 [-2.1 -4.4]]
[[-1.1 -2.4]
 [-2.1 -4.4]]
[[-1.1 -2.4]
 [-2.1 -4.4]]
[[11. 12.]
 [21. 22.]
 [31. 32.]]
[[1.e-01 2.e-01]
 [1.e+02 2.e+02]]
[[1.1e+00 1.2e+03]
 [2.1e+00 2.2e+03]
 [3.1e+00 3.2e+03]]
[[1.1e+00 1.2e+03]
 [2.1e+00 2.2e+03]
 [3.1e+00 3.2e+03]]
